apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    name: prometheus-2-server-conf
  name: prometheus-2-server-conf
  namespace: monitoring2
data:
  prometheus.yml: |-
    remote_write:
    - url: http://192.168.0.111:8080/receive
    global:
      scrape_interval: 1s
      evaluation_interval: 15s
    scrape_configs:
    - job_name: node
      metric_relabel_configs:
      - source_labels: [__name__]
        regex: node_netstat_Tcp_CurrEstab|node_sockstat_sockets_used|node_sockstat_TCP_inuse|node_timex_frequency_adjustment_ratio|node_sockstat_TCP_alloc
        action: keep
      static_configs:
      - targets: ['192.168.0.107:9100', '192.168.0.108:9100', '192.168.0.109:9100', '192.168.0.113:9100', '192.168.0.116:9100']
